[seiscomp] Fix seiscomp setup plugin support
When parsing description files the file order depends
on the system. Due to this reason it could happen that
plugin parameters would be read before the corresponding
module parameters. Error:

error: command 'setup' failed: seiscomp/etc/descriptions/scmaster.xml: duplicate module name: scmaster

This commit changes the handling of the setup groups so
that they are independent from the file order.